name: WarpSigns
main: falkirks\warpsigns\WarpSigns
author: Falkirks
version: 0.0.2
api: [3.0.0-ALPHA11]
depend: ["SimpleWarp"]
commands:
  signdoctor:
    permission: warpsigns.doctor
permissions:
  warpsigns:
    default: op
    children:
      warpsigns.doctor:
        default: op
      warpsigns.create:
        deafult: op
      warpsigns.use:
        deafult: true
